package cli

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	belayer "github.com/donovan-yohan/belayer"
	"github.com/spf13/cobra"
)

// defaultConfigYAML is written to .belayer/config.yaml on first init. The
// runtime + sandbox sections are commented out so a fresh project boots with
// noop defaults; users opt in by uncommenting and editing.
const defaultConfigYAML = `# .belayer/config.yaml — runtime + sandbox configuration for this project.
# Generated by 'belayer init'. Edit freely; belayer reads this on every run.

# Sandbox driver. The 'noop' driver runs agents in the host environment with
# no isolation. Switch to 'clamshell' (or another registered driver) and
# point 'policy' at a file under .belayer/policies/ to enable isolation.
#
# sandbox:
#   mode: clamshell
#   policy: .belayer/policies/standard.yaml

# Runtime hooks. Belayer can bring an integration environment up/down around
# a run (e.g. workbench services). When omitted, runs do not provision an
# environment — agents work directly against whatever is already running.
#
# runtime:
#   up: ./scripts/workbench-up.sh
#   health: ./scripts/workbench-health.sh
#   down: ./scripts/workbench-down.sh
#   endpoints:
#     - name: api
#       url: http://localhost:8080
`

// defaultPolicyYAML is a minimal placeholder so .belayer/policies/ is not
// empty after init. It is not wired in by the default config; users opt in by
// uncommenting the sandbox block in config.yaml.
const defaultPolicyYAML = `# .belayer/policies/standard.yaml — placeholder clamshell policy.
# 'belayer init' writes this so the policies/ directory has a starting point.
# Replace with a real policy when you switch sandbox.mode to 'clamshell'.
#
# See docs/design-docs/ for the full policy schema.
version: 5
sandbox:
  user: sandbox
  group: sandbox
  work_dir: /workspace
process:
  no_new_privileges: true
  drop_capabilities: ['ALL']
  read_only_rootfs: true
network:
  mode: proxy
`

func newInitCmd() *cobra.Command {
	var target string
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold .belayer/ in the current project",
		Long: `Create .belayer/{config.yaml,policies/,agents/} in the target directory
and copy the shipped default agents (supervisor, pm, web-dev, backend-dev, qa,
reviewer) into .belayer/agents/.

Idempotent: re-running prints a notice and exits 0 without overwriting. Use
--force to refresh .belayer/agents/ from the shipped defaults (useful when
upgrading belayer); existing config.yaml and policies/ are never overwritten.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()

			dir := target
			if dir == "" {
				cwd, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("resolve target directory: %w", err)
				}
				dir = cwd
			}
			absDir, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolve target directory: %w", err)
			}

			belayerDir := filepath.Join(absDir, ".belayer")
			result, err := scaffold(belayerDir, force)
			if err != nil {
				return err
			}

			if result.alreadyInitialized && !force {
				fmt.Fprintf(out, "belayer already initialized at %s (refreshed %d bridge file(s))\n",
					belayerDir, result.bridgeRefreshed)
				return nil
			}

			for _, line := range result.created {
				fmt.Fprintln(out, line)
			}
			fmt.Fprintf(out, "\nbelayer initialized at %s (%d file(s) created)\n",
				belayerDir, len(result.created))
			return nil
		},
	}

	cmd.Flags().StringVar(&target, "target", "", "Target directory (default cwd)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite .belayer/agents/ from shipped defaults")
	return cmd
}

// scaffoldResult records what scaffold produced so callers can render output
// (or, in the auto-init path from `belayer run`, skip output entirely).
//
// bridgeRefreshed is separate from created because bridge files are always
// overwritten on every init — on re-init we want a one-line refresh summary
// rather than N lines of "+ .belayer/hermes_bridge/<file>" noise.
type scaffoldResult struct {
	alreadyInitialized bool
	created            []string
	bridgeRefreshed    int
}

// scaffold creates belayerDir and its standard children. It is the core init
// routine, separated from the cobra command so `belayer run` can call it
// directly.
//
// On re-init without --force, user-owned files (config.yaml, policies/,
// agents/) are not touched — the CLI reports "already initialized". The
// hermes_bridge/ tree is refreshed unconditionally on every call so the
// extracted copy always matches the binary version.
func scaffold(belayerDir string, force bool) (scaffoldResult, error) {
	var result scaffoldResult

	if info, err := os.Stat(belayerDir); err == nil {
		if !info.IsDir() {
			return result, fmt.Errorf("%s exists but is not a directory", belayerDir)
		}
		result.alreadyInitialized = true
	} else if !os.IsNotExist(err) {
		return result, fmt.Errorf("stat %s: %w", belayerDir, err)
	}

	for _, sub := range []string{"", "policies", "agents", "hermes_bridge"} {
		p := filepath.Join(belayerDir, sub)
		if err := os.MkdirAll(p, 0o755); err != nil {
			return result, fmt.Errorf("mkdir %s: %w", p, err)
		}
	}

	// Bridge extraction runs on every scaffold, not gated by --force. It is
	// machine-owned: the extracted tree is overwritten so it always matches
	// the running binary's embedded copy.
	bridgeRoot := filepath.Join(belayerDir, "hermes_bridge")
	bridgeCopied, err := copyDefaultBridge(bridgeRoot)
	if err != nil {
		return result, err
	}
	result.bridgeRefreshed = len(bridgeCopied)
	// On fresh init, surface bridge files in the created list so the user
	// sees what was written. On re-init we rely on bridgeRefreshed for the
	// one-line summary.
	if !result.alreadyInitialized {
		for _, p := range bridgeCopied {
			result.created = append(result.created, "  + "+relativize(belayerDir, p))
		}
	}

	// If already initialized and not --force, stop here — user-owned files
	// (config.yaml, policies/, agents/) remain untouched.
	if result.alreadyInitialized && !force {
		sort.Strings(result.created)
		return result, nil
	}

	configPath := filepath.Join(belayerDir, "config.yaml")
	if created, err := writeIfMissing(configPath, []byte(defaultConfigYAML)); err != nil {
		return result, err
	} else if created {
		result.created = append(result.created, "  + "+relativize(belayerDir, configPath))
	}

	policyPath := filepath.Join(belayerDir, "policies", "standard.yaml")
	if created, err := writeIfMissing(policyPath, []byte(defaultPolicyYAML)); err != nil {
		return result, err
	} else if created {
		result.created = append(result.created, "  + "+relativize(belayerDir, policyPath))
	}

	agentsRoot := filepath.Join(belayerDir, "agents")
	copied, err := copyDefaultAgents(agentsRoot, force)
	if err != nil {
		return result, err
	}
	for _, p := range copied {
		result.created = append(result.created, "  + "+relativize(belayerDir, p))
	}

	sort.Strings(result.created)

	// Update the project's .gitignore so per-run scratch directories under
	// .belayer/ (runs/, worktrees/) don't get committed, while leaving the
	// committed config (agents/, config.yaml, policies/) tracked.
	gitignoreNote, err := ensureGitignoreEntries(filepath.Dir(belayerDir))
	if err != nil {
		return result, err
	}
	if gitignoreNote != "" {
		result.created = append(result.created, gitignoreNote)
	}

	return result, nil
}

// gitignoreBlock is appended to the project .gitignore on first init. Entries
// are anchored with a leading slash so they only match at the repo root —
// nested .belayer/ inside subprojects (e.g. inside .belayer/worktrees/...)
// are not affected by these rules. The leading newline is a separator from
// preceding content; it is stripped when the file is created from scratch
// so the file doesn't start with a blank line.
//
// hermes_bridge/ is gitignored because the tree is extracted from the binary
// on every `belayer init` and always overwrites — committing it would drift
// against the binary version.
const gitignoreBlock = `
# belayer — per-run state (committed: agents/, config.yaml, policies/)
/.belayer/runs/
/.belayer/worktrees/
/.belayer/hermes_bridge/
`

const gitignoreMarker = "# belayer — per-run state"

// ensureGitignoreEntries appends gitignoreBlock to <project>/.gitignore when
// the marker is absent. Returns a one-line summary describing what changed,
// suitable for printing in the init summary; returns "" when no change was
// needed. Never modifies an existing line — only appends.
func ensureGitignoreEntries(projectDir string) (string, error) {
	path := filepath.Join(projectDir, ".gitignore")
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(existing), gitignoreMarker) {
		return "", nil
	}

	block := gitignoreBlock
	out := append([]byte{}, existing...)
	if len(out) == 0 {
		// Fresh file — drop the separator newline so the file starts with the marker.
		block = strings.TrimLeft(block, "\n")
	} else if out[len(out)-1] != '\n' {
		// Existing file without a trailing newline — add one so we don't merge
		// onto a previous incomplete line.
		out = append(out, '\n')
	}
	out = append(out, []byte(block)...)

	if err := os.WriteFile(path, out, 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	if len(existing) == 0 {
		return "  + .gitignore (created with belayer entries)", nil
	}
	return "  ~ .gitignore (appended belayer entries)", nil
}

// copyDefaultAgents walks the embedded agents/ tree and writes each file into
// dst. Files that already exist are skipped unless force is set, in which case
// they are overwritten — this is how `belayer init --force` upgrades a
// project's shipped agents while leaving user-added profiles intact.
func copyDefaultAgents(dst string, force bool) ([]string, error) {
	var written []string
	err := fs.WalkDir(belayer.DefaultAgents, "agents", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		// "agents" itself is the embed root; skip it — we already created dst.
		if path == "agents" {
			return nil
		}
		// Strip the leading "agents/" so paths land directly under dst.
		rel := strings.TrimPrefix(path, "agents/")
		out := filepath.Join(dst, rel)

		if d.IsDir() {
			if err := os.MkdirAll(out, 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", out, err)
			}
			return nil
		}

		if !force {
			if _, err := os.Stat(out); err == nil {
				return nil
			} else if !os.IsNotExist(err) {
				return fmt.Errorf("stat %s: %w", out, err)
			}
		}

		data, err := belayer.DefaultAgents.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}
		if err := os.WriteFile(out, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", out, err)
		}
		written = append(written, out)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return written, nil
}

// copyDefaultBridge walks the embedded hermes_bridge/ tree and writes each
// file into dst. Unlike copyDefaultAgents it always overwrites — the bridge
// is machine-generated Go+Python glue pinned to this binary's version, so a
// stale file on disk would produce a hard-to-debug version-skew bug.
//
// __pycache__ directories and *.pyc files are skipped so host bytecode from
// developer builds never leaks into projects.
func copyDefaultBridge(dst string) ([]string, error) {
	var written []string
	err := fs.WalkDir(belayer.DefaultBridge, "hermes_bridge", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "hermes_bridge" {
			return nil
		}
		rel := strings.TrimPrefix(path, "hermes_bridge/")
		// Skip bytecode: __pycache__ directories (prune the whole subtree) and
		// any straggler *.pyc files. The walk returns SkipDir to avoid
		// descending into __pycache__.
		base := filepath.Base(rel)
		if d.IsDir() && base == "__pycache__" {
			return fs.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(base, ".pyc") {
			return nil
		}
		out := filepath.Join(dst, rel)

		if d.IsDir() {
			if err := os.MkdirAll(out, 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", out, err)
			}
			return nil
		}

		data, err := belayer.DefaultBridge.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}
		if err := os.WriteFile(out, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", out, err)
		}
		written = append(written, out)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return written, nil
}

// writeIfMissing writes data to path only if path does not already exist.
// Returns true when a file was created, false when one was already present.
// Existing files are never touched — config.yaml and policies/ are
// user-owned once init has run.
func writeIfMissing(path string, data []byte) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// relativize trims a leading parent prefix from p so output paths stay short.
// It falls back to p when the prefix does not match.
func relativize(parent, p string) string {
	rel, err := filepath.Rel(filepath.Dir(parent), p)
	if err != nil {
		return p
	}
	return rel
}

// autoInitIfMissing is the entry point for `belayer run` to scaffold .belayer/
// without forcing the user to call `belayer init` first. Scaffold is invoked
// unconditionally so the embedded hermes_bridge/ tree is refreshed on every
// run, keeping the extracted copy in sync with the binary. On a fresh scaffold
// (no prior .belayer/) a notice is written to w; the bridge refresh on existing
// projects is silent to avoid log spam on the hot path.
func autoInitIfMissing(workdir string, w io.Writer) error {
	belayerDir := filepath.Join(workdir, ".belayer")
	result, err := scaffold(belayerDir, false)
	if err != nil {
		return err
	}
	if !result.alreadyInitialized {
		fmt.Fprintf(w, "Auto-initialized %s with default agents — review and tweak as needed before next run.\n", belayerDir)
	}
	return nil
}
