package cli

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	belayer "github.com/donovan-yohan/belayer"
	"github.com/spf13/cobra"
)

// defaultConfigYAML is written to .belayer/config.yaml on first init. The
// runtime + sandbox sections are commented out so a fresh project boots with
// noop defaults; users opt in by uncommenting and editing.
const defaultConfigYAML = `# .belayer/config.yaml — runtime + sandbox configuration for this project.
# Generated by 'belayer init'. Edit freely; belayer reads this on every run.

# Sandbox driver. The 'noop' driver runs agents in the host environment with
# no isolation. Switch to 'clamshell' (or another registered driver) and
# point 'policy' at a file under .belayer/policies/ to enable isolation.
#
# sandbox:
#   mode: clamshell
#   policy: .belayer/policies/standard.yaml

# Runtime hooks. Belayer can bring an integration environment up/down around
# a run (e.g. workbench services). When omitted, runs do not provision an
# environment — agents work directly against whatever is already running.
#
# runtime:
#   up: ./scripts/workbench-up.sh
#   health: ./scripts/workbench-health.sh
#   down: ./scripts/workbench-down.sh
#   endpoints:
#     - name: api
#       url: http://localhost:8080
`

// defaultPolicyYAML is a minimal placeholder so .belayer/policies/ is not
// empty after init. It is not wired in by the default config; users opt in by
// uncommenting the sandbox block in config.yaml.
const defaultPolicyYAML = `# .belayer/policies/standard.yaml — placeholder clamshell policy.
# 'belayer init' writes this so the policies/ directory has a starting point.
# Replace with a real policy when you switch sandbox.mode to 'clamshell'.
#
# See docs/design-docs/ for the full policy schema.
version: 5
sandbox:
  user: sandbox
  group: sandbox
  work_dir: /workspace
process:
  no_new_privileges: true
  drop_capabilities: ['ALL']
  read_only_rootfs: true
network:
  mode: proxy
`

func newInitCmd() *cobra.Command {
	var target string
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold .belayer/ in the current project",
		Long: `Create .belayer/{config.yaml,policies/,agents/} in the target directory
and copy the shipped default agents (supervisor, pm, web-dev, backend-dev, qa,
reviewer) into .belayer/agents/.

Idempotent: re-running prints a notice and exits 0 without overwriting. Use
--force to refresh .belayer/agents/ from the shipped defaults (useful when
upgrading belayer); existing config.yaml and policies/ are never overwritten.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()

			dir := target
			if dir == "" {
				cwd, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("resolve target directory: %w", err)
				}
				dir = cwd
			}
			absDir, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolve target directory: %w", err)
			}

			belayerDir := filepath.Join(absDir, ".belayer")
			result, err := scaffold(belayerDir, force)
			if err != nil {
				return err
			}

			if result.alreadyInitialized && !force {
				fmt.Fprintf(out, "belayer already initialized at %s\n", belayerDir)
				return nil
			}

			for _, line := range result.created {
				fmt.Fprintln(out, line)
			}
			fmt.Fprintf(out, "\nbelayer initialized at %s (%d file(s) created)\n",
				belayerDir, len(result.created))
			return nil
		},
	}

	cmd.Flags().StringVar(&target, "target", "", "Target directory (default cwd)")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite .belayer/agents/ from shipped defaults")
	return cmd
}

// scaffoldResult records what scaffold produced so callers can render output
// (or, in the auto-init path from `belayer run`, skip output entirely).
type scaffoldResult struct {
	alreadyInitialized bool
	created            []string
}

// scaffold creates belayerDir and its standard children. It is the core init
// routine, separated from the cobra command so `belayer run` can call it
// directly. When force is false and belayerDir exists, it is a no-op.
func scaffold(belayerDir string, force bool) (scaffoldResult, error) {
	var result scaffoldResult

	if _, err := os.Stat(belayerDir); err == nil {
		result.alreadyInitialized = true
		if !force {
			return result, nil
		}
	} else if !os.IsNotExist(err) {
		return result, fmt.Errorf("stat %s: %w", belayerDir, err)
	}

	for _, sub := range []string{"", "policies", "agents"} {
		p := filepath.Join(belayerDir, sub)
		if err := os.MkdirAll(p, 0o755); err != nil {
			return result, fmt.Errorf("mkdir %s: %w", p, err)
		}
	}

	configPath := filepath.Join(belayerDir, "config.yaml")
	if created, err := writeIfMissing(configPath, []byte(defaultConfigYAML)); err != nil {
		return result, err
	} else if created {
		result.created = append(result.created, "  + "+relativize(belayerDir, configPath))
	}

	policyPath := filepath.Join(belayerDir, "policies", "standard.yaml")
	if created, err := writeIfMissing(policyPath, []byte(defaultPolicyYAML)); err != nil {
		return result, err
	} else if created {
		result.created = append(result.created, "  + "+relativize(belayerDir, policyPath))
	}

	agentsRoot := filepath.Join(belayerDir, "agents")
	copied, err := copyDefaultAgents(agentsRoot, force)
	if err != nil {
		return result, err
	}
	for _, p := range copied {
		result.created = append(result.created, "  + "+relativize(belayerDir, p))
	}

	sort.Strings(result.created)

	// Update the project's .gitignore so per-run scratch directories under
	// .belayer/ (runs/, worktrees/) don't get committed, while leaving the
	// committed config (agents/, config.yaml, policies/) tracked.
	gitignoreNote, err := ensureGitignoreEntries(filepath.Dir(belayerDir))
	if err != nil {
		return result, err
	}
	if gitignoreNote != "" {
		result.created = append(result.created, gitignoreNote)
	}

	return result, nil
}

// gitignoreBlock is appended to the project .gitignore on first init. Entries
// are anchored with a leading slash so they only match at the repo root —
// nested .belayer/ inside subprojects (e.g. inside .belayer/worktrees/...)
// are not affected by these rules.
const gitignoreBlock = `
# belayer — per-run state (committed: agents/, config.yaml, policies/)
/.belayer/runs/
/.belayer/worktrees/
`

const gitignoreMarker = "# belayer — per-run state"

// ensureGitignoreEntries appends gitignoreBlock to <project>/.gitignore when
// the marker is absent. Returns a one-line summary describing what changed,
// suitable for printing in the init summary; returns "" when no change was
// needed. Never modifies an existing line — only appends.
func ensureGitignoreEntries(projectDir string) (string, error) {
	path := filepath.Join(projectDir, ".gitignore")
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(existing), gitignoreMarker) {
		return "", nil
	}

	out := append([]byte{}, existing...)
	// Ensure a trailing newline before the appended block so we don't merge
	// onto a previous incomplete line.
	if len(out) > 0 && out[len(out)-1] != '\n' {
		out = append(out, '\n')
	}
	out = append(out, []byte(gitignoreBlock)...)

	if err := os.WriteFile(path, out, 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	if len(existing) == 0 {
		return "  + .gitignore (created with belayer entries)", nil
	}
	return "  ~ .gitignore (appended belayer entries)", nil
}

// copyDefaultAgents walks the embedded agents/ tree and writes each file into
// dst. Files that already exist are skipped unless force is set, in which case
// they are overwritten — this is how `belayer init --force` upgrades a
// project's shipped agents while leaving user-added profiles intact.
func copyDefaultAgents(dst string, force bool) ([]string, error) {
	var written []string
	err := fs.WalkDir(belayer.DefaultAgents, "agents", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		// "agents" itself is the embed root; skip it — we already created dst.
		if path == "agents" {
			return nil
		}
		// Strip the leading "agents/" so paths land directly under dst.
		rel := strings.TrimPrefix(path, "agents/")
		out := filepath.Join(dst, rel)

		if d.IsDir() {
			if err := os.MkdirAll(out, 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", out, err)
			}
			return nil
		}

		if !force {
			if _, err := os.Stat(out); err == nil {
				return nil
			} else if !os.IsNotExist(err) {
				return fmt.Errorf("stat %s: %w", out, err)
			}
		}

		data, err := belayer.DefaultAgents.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}
		if err := os.WriteFile(out, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", out, err)
		}
		written = append(written, out)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return written, nil
}

// writeIfMissing writes data to path only if path does not already exist.
// Returns true when a file was created, false when one was already present.
// Existing files are never touched — config.yaml and policies/ are
// user-owned once init has run.
func writeIfMissing(path string, data []byte) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// relativize trims a leading parent prefix from p so output paths stay short.
// It falls back to p when the prefix does not match.
func relativize(parent, p string) string {
	rel, err := filepath.Rel(filepath.Dir(parent), p)
	if err != nil {
		return p
	}
	return rel
}

// autoInitIfMissing is the entry point for `belayer run` to scaffold .belayer/
// without forcing the user to call `belayer init` first. It writes a notice
// to w when scaffolding actually runs and stays silent on the no-op path.
func autoInitIfMissing(workdir string, w io.Writer) error {
	belayerDir := filepath.Join(workdir, ".belayer")
	if _, err := os.Stat(belayerDir); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", belayerDir, err)
	}

	result, err := scaffold(belayerDir, false)
	if err != nil {
		return err
	}
	if !result.alreadyInitialized {
		fmt.Fprintf(w, "Auto-initialized %s with default agents — review and tweak as needed before next run.\n", belayerDir)
	}
	return nil
}
