package daemon

import (
	"fmt"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// startDaemonWithTCP starts a daemon with the given config, waits for it to be
// reachable on both the unix socket and TCP port, and returns the daemon plus a
// cleanup function. The Config must have TCPAddr set.
func startDaemonWithTCP(t *testing.T, cfg Config) (*Daemon, int) {
	t.Helper()

	// Darwin limits sun_path to 104 bytes; use /tmp for socket files.
	socketDir, err := os.MkdirTemp("/tmp", "bl")
	if err != nil {
		t.Fatalf("MkdirTemp: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(socketDir) })
	cfg.SocketPath = filepath.Join(socketDir, "d.sock")
	if cfg.DBPath == "" {
		cfg.DBPath = filepath.Join(t.TempDir(), "belayer.db")
	}

	d, err := New(cfg)
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	ctx := t.Context()
	serveErr := make(chan error, 1)
	go func() { serveErr <- d.Start(ctx) }()
	t.Cleanup(func() {
		select {
		case <-serveErr:
		case <-time.After(3 * time.Second):
		}
	})

	// Wait for the unix socket to become reachable (guarantees TCP is bound too).
	for deadline := time.Now().Add(3 * time.Second); time.Now().Before(deadline); {
		select {
		case startErr := <-serveErr:
			t.Fatalf("Start returned early: %v", startErr)
		default:
		}
		c, dialErr := net.Dial("unix", cfg.SocketPath)
		if dialErr == nil {
			c.Close()
			break
		}
		time.Sleep(10 * time.Millisecond)
	}

	port := d.TCPPort()
	if port == 0 {
		t.Fatal("daemon TCP port is 0 after Start")
	}
	return d, port
}

// TestAuth_UnixSocketBypassesAuth verifies that requests via the unix socket
// path (d.server.Handler) do NOT require an Authorization header, even when
// AuthToken is set.
func TestAuth_UnixSocketBypassesAuth(t *testing.T) {
	d := testDaemon(t)
	// Simulate a configured auth token.
	d.authToken = "test123"

	// Hit the unix-socket handler directly (no middleware).
	rr := httptest.NewRecorder()
	req := httptest.NewRequest("GET", "/sessions", nil)
	// No Authorization header.
	d.server.Handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("unix socket GET /sessions without auth: got %d, want 200", rr.Code)
	}
}

// TestAuth_TCPRejectsMissingBearer verifies that a TCP request without an
// Authorization: Bearer header is rejected with 401.
func TestAuth_TCPRejectsMissingBearer(t *testing.T) {
	_, port := startDaemonWithTCP(t, Config{
		TCPAddr:   "127.0.0.1:0",
		AuthToken: "test123",
	})

	resp, err := http.Get(fmt.Sprintf("http://127.0.0.1:%d/sessions", port))
	if err != nil {
		t.Fatalf("GET /sessions: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", resp.StatusCode)
	}
}

// TestAuth_TCPAcceptsValidBearer verifies that a TCP request with the correct
// bearer token is accepted.
func TestAuth_TCPAcceptsValidBearer(t *testing.T) {
	_, port := startDaemonWithTCP(t, Config{
		TCPAddr:   "127.0.0.1:0",
		AuthToken: "test123",
	})

	req, _ := http.NewRequest("GET", fmt.Sprintf("http://127.0.0.1:%d/sessions", port), nil)
	req.Header.Set("Authorization", "Bearer test123")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("GET /sessions with auth: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

// TestAuth_HealthSkipsAuth verifies that GET /health on the TCP listener
// succeeds without an Authorization header.
func TestAuth_HealthSkipsAuth(t *testing.T) {
	_, port := startDaemonWithTCP(t, Config{
		TCPAddr:   "127.0.0.1:0",
		AuthToken: "test123",
	})

	resp, err := http.Get(fmt.Sprintf("http://127.0.0.1:%d/health", port))
	if err != nil {
		t.Fatalf("GET /health: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}
}

// TestAuth_TokenAutoGenerated verifies that when TCPAddr is set but AuthToken
// is empty, New() generates a non-empty token.
func TestAuth_TokenAutoGenerated(t *testing.T) {
	d, err := New(Config{
		DBPath:     filepath.Join(t.TempDir(), "belayer.db"),
		SocketPath: filepath.Join(t.TempDir(), "d.sock"),
		TCPAddr:    "127.0.0.1:0",
		// AuthToken intentionally left empty.
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	if d.authToken == "" {
		t.Fatal("authToken is empty; expected auto-generated token when TCPAddr is set")
	}
}

// --- CORS tests ---

// TestCORS_AllowedOriginGetsHeader verifies that a preflight from an allowed
// origin returns 204 with the correct Access-Control-Allow-Origin header.
func TestCORS_AllowedOriginGetsHeader(t *testing.T) {
	d := testDaemon(t)
	d.config.CORSOrigins = []string{"https://app.example"}

	handler := d.corsMiddleware(d.authMiddleware(d.server.Handler))

	req := httptest.NewRequest("OPTIONS", "/sessions", nil)
	req.Header.Set("Origin", "https://app.example")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusNoContent {
		t.Fatalf("OPTIONS preflight: got %d, want 204", rr.Code)
	}
	got := rr.Header().Get("Access-Control-Allow-Origin")
	if got != "https://app.example" {
		t.Fatalf("Access-Control-Allow-Origin: got %q, want %q", got, "https://app.example")
	}
}

// TestCORS_DisallowedOrigin verifies that a preflight from a non-allowed origin
// is rejected with 403.
func TestCORS_DisallowedOrigin(t *testing.T) {
	d := testDaemon(t)
	d.config.CORSOrigins = []string{"https://app.example"}

	handler := d.corsMiddleware(d.authMiddleware(d.server.Handler))

	req := httptest.NewRequest("OPTIONS", "/sessions", nil)
	req.Header.Set("Origin", "https://evil.example")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if rr.Code != http.StatusForbidden {
		t.Fatalf("expected 403 for disallowed origin, got %d", rr.Code)
	}
}

// TestCORS_NoStar verifies that the CORS middleware never emits a wildcard
// Access-Control-Allow-Origin header.
func TestCORS_NoStar(t *testing.T) {
	d := testDaemon(t)
	d.config.CORSOrigins = []string{"https://app.example"}

	handler := d.corsMiddleware(d.server.Handler)

	req := httptest.NewRequest("OPTIONS", "/sessions", nil)
	req.Header.Set("Origin", "https://app.example")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	v := rr.Header().Get("Access-Control-Allow-Origin")
	if v == "*" {
		t.Fatal("CORS middleware emitted wildcard Access-Control-Allow-Origin: *")
	}
}

// TestCORS_NoCredentialsHeader verifies that the CORS middleware never emits
// Access-Control-Allow-Credentials.
func TestCORS_NoCredentialsHeader(t *testing.T) {
	d := testDaemon(t)
	d.config.CORSOrigins = []string{"https://app.example"}

	handler := d.corsMiddleware(d.server.Handler)

	req := httptest.NewRequest("OPTIONS", "/sessions", nil)
	req.Header.Set("Origin", "https://app.example")
	rr := httptest.NewRecorder()
	handler.ServeHTTP(rr, req)

	if v := rr.Header().Get("Access-Control-Allow-Credentials"); v != "" {
		t.Fatalf("expected no Access-Control-Allow-Credentials header, got %q", v)
	}
}

